services:
  web:
    build:
      context: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7001:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    restart: always

  celery:
    build:
      context: .
    command: celery -A shop_api worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  celery_beat:
    build:
      context: .
    command: celery -A shop_api beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  flower:
    build:
      context: .
    command: celery -A shop_api flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

volumes:
  db-data:
  redis_data: